### ISSUE TITLE
InvalidArgumentException: Given URI "api.telegram.org" does not contain a valid host IP

### ISSUE THREAD

**Issue by 4n70w4** [unreal4u/telegram-api#149]
## Which version are you using?

v3.4.1

Output:
```
app.ERROR: InvalidArgumentException: Given URI "api.telegram.org" does not contain a valid host IP in /var/www/vendor/react/socket/src/TcpConnector.php:34 Stack trace: #0 /var/www/vendor/react/socket/src/SecureConnector.php(44): React\Socket\TcpConnector->connect('tcp://api.teleg...') #1 /var/www/vendor/react/socket/src/TimeoutConnector.php(24): React\Socket\SecureConnector->connect('api.telegram.or...') #2 /var/www/vendor/react/socket/src/Connector.php(136): React\Socket\TimeoutConnector->connect('tls://api.teleg...') #3 /var/www/vendor/react/http-client/src/Request.php(265): React\Socket\Connector->connect('tls://api.teleg...') #4 /var/www/vendor/react/http-client/src/Request.php(57): React\HttpClient\Request->connect() #5 /var/www/vendor/react/http-client/src/Request.php(105): React\HttpClient\Request->writeHead() #6 /var/www/vendor/react/http-client/src/Request.php(118): React\HttpClient\Request->write('offset=85149292...') #7 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(86): React\HttpClient\Request->end('offset=85149292...') #8 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(53): unreal4u\TelegramAPI\HttpClientRequestHandler->processRequest(Object(React\HttpClient\Request), 'offset=85149292...') #9 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(126): unreal4u\TelegramAPI\HttpClientRequestHandler->post('https://api.tel...', Array) #10 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(89): unreal4u\TelegramAPI\TgLog->sendRequestToTelegram(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates), Array) #11 /var/www/src/Command/MainTelegramCommand.php(85): unreal4u\TelegramAPI\TgLog->performApiRequest(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates)) #12 /var/www/vendor/symfony/console/Command/Command.php(255): App\Command\MainTelegramCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/vendor/symfony/framework-bundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/vendor/symfony/framework-bundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #19 {main}  Next unreal4u\TelegramAPI\Exceptions\ClientException: Given URI "api.telegram.org" does not contain a valid host IP in /var/www/vendor/react/socket/src/TcpConnector.php:34 Stack trace: #0 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): unreal4u\TelegramAPI\HttpClientRequestHandler->unreal4u\TelegramAPI\{closure}(Object(InvalidArgumentException)) #1 /var/www/vendor/react/http-client/src/Request.php(203): Evenement\EventEmitter->emit('error', Array) #2 /var/www/vendor/react/promise/src/RejectedPromise.php(25): React\HttpClient\Request->closeError(Object(InvalidArgumentException)) #3 /var/www/vendor/react/http-client/src/Request.php(83): React\Promise\RejectedPromise->then(Object(Closure), Array) #4 /var/www/vendor/react/http-client/src/Request.php(105): React\HttpClient\Request->writeHead() #5 /var/www/vendor/react/http-client/src/Request.php(118): React\HttpClient\Request->write('offset=85149292...') #6 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(86): React\HttpClient\Request->end('offset=85149292...') #7 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(53): unreal4u\TelegramAPI\HttpClientRequestHandler->processRequest(Object(React\HttpClient\Request), 'offset=85149292...') #8 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(126): unreal4u\TelegramAPI\HttpClientRequestHandler->post('https://api.tel...', Array) #9 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(89): unreal4u\TelegramAPI\TgLog->sendRequestToTelegram(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates), Array) #10 /var/www/src/Command/MainTelegramCommand.php(85): unreal4u\TelegramAPI\TgLog->performApiRequest(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates)) #11 /var/www/vendor/symfony/console/Command/Command.php(255): App\Command\MainTelegramCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/vendor/symfony/framework-bundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/vendor/symfony/framework-bundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #18 {main} [] []
[2022-09-17 23:32:33] app.ERROR: Exception on promise: InvalidArgumentException: Given URI "api.telegram.org" does not contain a valid host IP in /var/www/vendor/react/socket/src/TcpConnector.php:34 Stack trace: #0 /var/www/vendor/react/socket/src/SecureConnector.php(44): React\Socket\TcpConnector->connect('tcp://api.teleg...') #1 /var/www/vendor/react/socket/src/TimeoutConnector.php(24): React\Socket\SecureConnector->connect('api.telegram.or...') #2 /var/www/vendor/react/socket/src/Connector.php(136): React\Socket\TimeoutConnector->connect('tls://api.teleg...') #3 /var/www/vendor/react/http-client/src/Request.php(265): React\Socket\Connector->connect('tls://api.teleg...') #4 /var/www/vendor/react/http-client/src/Request.php(57): React\HttpClient\Request->connect() #5 /var/www/vendor/react/http-client/src/Request.php(105): React\HttpClient\Request->writeHead() #6 /var/www/vendor/react/http-client/src/Request.php(118): React\HttpClient\Request->write('offset=85149292...') #7 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(86): React\HttpClient\Request->end('offset=85149292...') #8 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(53): unreal4u\TelegramAPI\HttpClientRequestHandler->processRequest(Object(React\HttpClient\Request), 'offset=85149292...') #9 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(126): unreal4u\TelegramAPI\HttpClientRequestHandler->post('https://api.tel...', Array) #10 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(89): unreal4u\TelegramAPI\TgLog->sendRequestToTelegram(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates), Array) #11 /var/www/src/Command/MainTelegramCommand.php(85): unreal4u\TelegramAPI\TgLog->performApiRequest(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates)) #12 /var/www/vendor/symfony/console/Command/Command.php(255): App\Command\MainTelegramCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/vendor/symfony/framework-bundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/vendor/symfony/framework-bundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #19 {main}  Next unreal4u\TelegramAPI\Exceptions\ClientException: Given URI "api.telegram.org" does not contain a valid host IP in /var/www/vendor/react/socket/src/TcpConnector.php:34 Stack trace: #0 /var/www/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): unreal4u\TelegramAPI\HttpClientRequestHandler->unreal4u\TelegramAPI\{closure}(Object(InvalidArgumentException)) #1 /var/www/vendor/react/http-client/src/Request.php(203): Evenement\EventEmitter->emit('error', Array) #2 /var/www/vendor/react/promise/src/RejectedPromise.php(25): React\HttpClient\Request->closeError(Object(InvalidArgumentException)) #3 /var/www/vendor/react/http-client/src/Request.php(83): React\Promise\RejectedPromise->then(Object(Closure), Array) #4 /var/www/vendor/react/http-client/src/Request.php(105): React\HttpClient\Request->writeHead() #5 /var/www/vendor/react/http-client/src/Request.php(118): React\HttpClient\Request->write('offset=85149292...') #6 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(86): React\HttpClient\Request->end('offset=85149292...') #7 /var/www/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(53): unreal4u\TelegramAPI\HttpClientRequestHandler->processRequest(Object(React\HttpClient\Request), 'offset=85149292...') #8 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(126): unreal4u\TelegramAPI\HttpClientRequestHandler->post('https://api.tel...', Array) #9 /var/www/vendor/unreal4u/telegram-api/src/TgLog.php(89): unreal4u\TelegramAPI\TgLog->sendRequestToTelegram(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates), Array) #10 /var/www/src/Command/MainTelegramCommand.php(85): unreal4u\TelegramAPI\TgLog->performApiRequest(Object(unreal4u\TelegramAPI\Telegram\Methods\GetUpdates)) #11 /var/www/vendor/symfony/console/Command/Command.php(255): App\Command\MainTelegramCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /var/www/vendor/symfony/console/Application.php(953): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 /var/www/vendor/symfony/framework-bundle/Console/Application.php(87): Symfony\Component\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(App\Command\MainTelegramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/vendor/symfony/framework-bundle/Console/Application.php(73): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #18 {main} {"e":"[object] (unreal4u\\TelegramAPI\\Exceptions\\ClientException(code: 0): Given URI \"api.telegram.org\" does not contain a valid host IP at /var/www/vendor/react/socket/src/TcpConnector.php:34, InvalidArgumentException(code: 0): Given URI \"api.telegram.org\" does not contain a valid host IP at /var/www/vendor/react/socket/src/TcpConnector.php:34)"} []
```

## Description of problem

But

```
ping api.telegram.org
```

```
PING api.telegram.org (149.154.167.220) 56(84) bytes of data.
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=1 ttl=50 time=39.0 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=2 ttl=50 time=54.8 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=3 ttl=50 time=39.0 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=4 ttl=50 time=39.0 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=5 ttl=50 time=39.0 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=6 ttl=50 time=39.0 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=7 ttl=50 time=39.1 ms
```

**Comment by unreal4u** [comment]
Hi! 

Are you using a proxy, docker or something that might affect the DNS resolution within PHP?

Greetings.
