### ISSUE TITLE
3.3.3: Exception not raised?

### ISSUE THREAD

**Issue by daviddavo** [unreal4u/telegram-api#79]
Hi. I created a bot using your API and Reactphp Event loop. The thing is that, when this ClientException happens, I can't catch it.
The Webhook code looks like this:
``` php
$logger = new Logger('cxtbot');
$logger->pushHandler(new RotatingFileHandler(__DIR__ . "/../logs/phplog.log", 30, Logger::DEBUG));

$loop = Factory::create();
$httpClient = new HttpClientRequestHandler($loop);
$db = new database(DB_SERVER, DB_USER, DB_PASSWORD, $logger);

$updateData = json_decode(file_get_contents('php://input'), true);

try {
  $bot = new mainBot(BOT_TOKEN, $logger, $httpClient, $db);
  $bot->webHookHandler($updateData);
} catch (\Exception $e) {
  $logger->error("EXCEPTION: " . $e->getMessage());
}
```
`/var/log/httpd/error_log` doesn't show anything related, but in the Monolog log (`../logs/phplog.log`) I can see this:
```
[2018-02-09 22:35:42] cxtbot.DEBUG: Request for async API call, resetting internal values ["unreal4u\\TelegramAPI\\Telegram\\Methods\\EditMessageText"] []
[2018-02-09 22:35:42] cxtbot.DEBUG: About to perform async HTTP call to Telegram's API [] []
[2018-02-09 22:35:42] cxtbot.INFO: About to perform API request {"method":"EditMessageText"} []
[2018-02-09 22:35:43] cxtbot.ERROR: unreal4u\TelegramAPI\Exceptions\ClientException: Bad Request: message is not modified in /srv/http/cuentosxtelefono18/vendor/unreal4u/telegram-api/src/InternalFunctionality/TelegramResponse.php:50 Stack trace: #0 /srv/http/cuentosxtelefono18/vendor/unreal4u/telegram-api/src/InternalFunctionality/TelegramResponse.php(33): unreal4u\TelegramAPI\InternalFunctionality\TelegramResponse->fillRawData('{"ok":false,"er...') #1 /srv/http/cuentosxtelefono18/vendor/unreal4u/telegram-api/src/HttpClientRequestHandler.php(73): unreal4u\TelegramAPI\InternalFunctionality\TelegramResponse->__construct('{"ok":false,"er...', Array) #2 /srv/http/cuentosxtelefono18/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): unreal4u\TelegramAPI\HttpClientRequestHandler->unreal4u\TelegramAPI\{closure}() #3 /srv/http/cuentosxtelefono18/vendor/react/http-client/src/Response.php(92): Evenement\EventEmitter->emit('end') #4 /srv/http/cuentosxtelefono18/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\HttpClient\Response->handleEnd() #5 /srv/http/cuentosxtelefono18/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('end', Array) #6 /srv/http/cuentosxtelefono18/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}() #7 /srv/http/cuentosxtelefono18/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('end') #8 [internal function]: React\Stream\DuplexResourceStream->handleData(Resource id #120, Object(React\EventLoop\StreamSelectLoop)) #9 /srv/http/cuentosxtelefono18/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func(Array, Resource id #120, Object(React\EventLoop\StreamSelectLoop)) #10 /srv/http/cuentosxtelefono18/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL) #11 /srv/http/cuentosxtelefono18/telegram/index.php(34): React\EventLoop\StreamSelectLoop->run() #12 {main} [] []
```
Why does it show the error but I can't catch it?

**Comment by unreal4u** [comment]
Hi! 

I am on the phone right now so can't go too deep in details, but adding a second closure will allow you to handle exceptions. 

There is an example of this in the following file:  https://github.com/unreal4u/telegram-api/blob/master/examples/get-chat-member.php

Greetings

**Comment by unreal4u** [comment]
Hi! Did the above solve your problem?

If there isn't a response in a few days, I'll close this one, you can always reopen it or make a new issue ;)

Greetings.

**Comment by daviddavo** [comment]
Yes, that was exactly the problem. Sorry for not closing it before
